//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SubmittedUser { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual User User { get; set; }
    }
}
